name: 'lint my project'
on:
  push:
  pull-request:

jobs:
  lint-job:
   runs-on: ubuntu-latest
   steps:
     - uses: action/checout@v2
     - uses: action/setup-node@v1
       name = 'setup node'
         with:
         node-version: '14.x'
     - name: 'install'
       run: make install
     - name: 'run linter'
       run: make lint
